### ISSUE TITLE
Error example e3

### ISSUE THREAD

**Issue by HvanderStok** [RWTH-EBC/ebcpy#79]
In the example `e3_dymola_example.py` the function `save_for_reproduction()` from the DymolaAPI is called after Dymola is closed which causes the following error:
```
Traceback (most recent call last):
  File "D:\sbg-hst\Repos\ebcpy\examples\e3_dymola_example.py", line 183, in <module>
    main(
  File "D:\sbg-hst\Repos\ebcpy\examples\e3_dymola_example.py", line 173, in main
    file = dym_api.save_for_reproduction(
  File "D:\sbg-hst\Repos\ebcpy\ebcpy\simulationapi\dymola_api.py", line 869, in save_for_reproduction
    self.dymola.ExecuteCommand("list();")
AttributeError: 'NoneType' object has no attribute 'ExecuteCommand'
```

**Comment by HvanderStok** [comment]
I moved the function call for the closing of Dymola, but this results in a new error:
```
Traceback (most recent call last):
  File "D:\sbg-hst\Repos\ebcpy\examples\e3_dymola_example.py", line 184, in <module>
    main(
  File "D:\sbg-hst\Repos\ebcpy\examples\e3_dymola_example.py", line 147, in main
    file = dym_api.save_for_reproduction(
  File "D:\sbg-hst\Repos\ebcpy\ebcpy\simulationapi\dymola_api.py", line 882, in save_for_reproduction
    packages = self.get_packages()
  File "D:\sbg-hst\Repos\ebcpy\ebcpy\simulationapi\dymola_api.py", line 822, in get_packages
    for pack in packages:
TypeError: 'NoneType' object is not iterable
```
In `get_packages`  the following function returns nothing:
```
packages = self.dymola.ExecuteCommand(
            'ModelManagement.Structure.AST.Misc.ClassesInPackage("")'
        ) 
```
Can this be caused from the used Dymola version (I used Dymola 2021)? My solution would be to get the packages from `self.packages`. @FWuellhorst what do you think on this?

**Comment by FWuellhorst** [comment]
Thanks for noticing! Yes, moving the .close() should work.
Interesting regarding the ModelManagement. Maybe you don't have that library? If so, then returning self.packages and logging an error should be the best way forward.
